from .weather_prediction import WeatherPredictionStrategy
from .spread_trading import SpreadTradingStrategy
from .crypto_momentum import CryptoMomentumStrategy
from .longshot_weather import LongshotWeatherStrategy
